apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-proxy-tls
  namespace: pomerium
spec:
  dnsNames:
  - 'authenticate.bigasterisk.com'
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  secretName: pomerium-proxy-tls