apiVersion: v1
kind: PersistentVolume
metadata:
  name: autocert-data
  labels:
    type: local
spec:
  storageClassName: manual
  hostPath:
    path: "/opt/pomerium-autocert"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: pomerium
    name: autocert-data
